version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_mariadb_password
      MYSQL_DATABASE: db_test_cdc
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  connect:
    image: debezium/connect:latest
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./config/connect-distributed.properties:/etc/kafka/connect-distributed.properties
      - ./config/mariadb-connector.json:/mariadb-connector.json
    depends_on:
      - kafka
      - mariadb
